### ISSUE TITLE
Fails with latest Leiningen

### ISSUE THREAD

**Issue by seancorfield** [boxed/midje-readme#12]
Fails with this exception due to `with-out-str` not capturing output of `eval-in` with latest Leiningen:
```
java.lang.RuntimeException: EOF while reading
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.LispReader.read(LispReader.java:246)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.LispReader.read(LispReader.java:185)
	at clojure.lang.RT.readString(RT.java:1821)
	at clojure.lang.RT.readString(RT.java:1816)
	at clojure.core$read_string.invoke(core.clj:3663)
	at midje_readme.plugin$middleware.invoke(plugin.clj:71)
	at clojure.lang.Var.invoke(Var.java:379)
	at leiningen.core.project$apply_middleware.invoke(project.clj:746)
```
A possible fix is to change line 71 to this:
```
  (let [used-clojure-version (read-string (with-out-str (eval-in (assoc project :eval-in :classloader) '(prn *clojure-version*))))]
```
But I suspect this may not work on earlier versions of Leiningen?

**Comment by boxed** [comment]
Hmm.. I wonder why we do it like that at all.. why can't that line just be 

```clojure
(let [used-clojure-version (eval-in project '*clojure-version*)]
```

I haven't really looked at this code for ages and @bsvingen has rewritten basically the entire thing since last time, so I don't know what to make of this :P

**Comment by seancorfield** [comment]
Because `eval-in` returns `nil`. So you have to print the output, capture it, and read it.

What seems to have changed in Leiningen "recently" is that the default `eval-in` uses a subprocess and thus you can't capture the output using `with-out-str`. The change to evaluate in the `:classloader` allows capturing the output.

**Comment by seancorfield** [comment]
Thank you!

**Comment by seancorfield** [comment]
Just FYI, the fix does not work on Leiningen 2.5.1 (as I found out when trying to get Travis to run the clj-time builds with the 1.0.9 midje-readme: I ended up forcing Travis to upgrade Leiningen to 2.5.3).

Just in case you want to figure out a fix that isn't quite so version sensitive...

**Comment by bsvingen** [comment]
Would it be worth the effort? I'm forcing the same upgrade myself on [bsvingen/squirrel](https://github.com/bsvingen/squirrel), but I am not aware of any cases where running on old Leiningen versions is a requirement.

**Comment by seancorfield** [comment]
I wonder when `:classloader` came in? If that works on 2.5.1 it's marginally more backward compatible and a less intrusive change than what's in there now.

But you're right: aside from the inconvenience of Travis running 2.5.1 instead of 2.5.3, which only affects the handful of users who a) use midje-readme and b) also run CI on Travis with it, it's not worth spending more time on.

I hadn't encountered midje-readme until someone integrated it into clj-time and it wasn't being leveraged very much until I decided to revamp the whole README this past week. It's a very cool idea. Thank you!

**Comment by boxed** [comment]
Thanks! And thanks on behalf of my awesome contributors/maintainers who are really carrying the load for this project!
